# Generated by Django 5.0.6 on 2024-07-06 23:58

import djgeojson.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('boundary', djgeojson.fields.GeometryField()),
                ('is_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=150)),
                ('short_address', models.CharField(max_length=150)),
                ('declared_date', models.DateTimeField()),
                ('ward_number', models.IntegerField()),
                ('parcel_number', models.IntegerField()),
                ('latlon', djgeojson.fields.PointField(blank=True, null=True)),
                ('corrected_address', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('boundary', djgeojson.fields.GeometryField()),
                ('boundary_area', models.FloatField(null=True)),
                ('neighborhoods_map_enabled', models.BooleanField(default=True)),
                ('properties', models.ManyToManyField(to='okcvacants.property')),
            ],
        ),
    ]
