# Generated by Django 2.2 on 2019-04-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=150)),
                ('declared_date', models.DateTimeField()),
                ('ward_number', models.IntegerField()),
                ('parcel_number', models.IntegerField()),
            ],
        ),
    ]
