# Generated by Django 2.2 on 2019-04-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('okcvacants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='lat',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='property',
            name='lon',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=12),
        ),
    ]
