# Generated by Django 2.2 on 2019-04-25 04:17

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('okcvacants', '0002_auto_20190421_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latlon',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0),
                                                                 srid=4326),
        ),
    ]
