# Generated by Django 2.2 on 2019-04-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('okcvacants', '0005_auto_20190427_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='boundary_area',
            field=models.FloatField(null=True),
        ),
    ]
