# Generated by Django 2.2 on 2019-05-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('okcvacants', '0007_auto_20190504_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='properties',
            field=models.ManyToManyField(to='okcvacants.Property'),
        ),
    ]
