# Generated by Django 2.2 on 2019-05-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('okcvacants', '0009_auto_20190505_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='corrected_address',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
