# Generated by Django 2.2 on 2019-05-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('okcvacants', '0010_property_corrected_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='neighborhoods_map_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
