# Generated by Django 2.2 on 2019-05-11 22:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('okcvacants', '0011_neighborhood_neighborhoods_map_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('boundary', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('is_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
