# Generated by Django 2.2 on 2019-05-16 02:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('okcvacants', '0012_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='latlon',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
