# Generated by Django 2.2 on 2019-06-02 02:51

from django.db import migrations, models
from django.apps import apps

import re

class Migration(migrations.Migration):
    # needed to remove additional code to "import" address into short_address because of issues with error:
    # "django.db.utils.ProgrammingError: column "census_tract_id" of relation "okcvacants_property" does not exist"
    # during later migration
    dependencies = [
        ('okcvacants', '0013_auto_20190516_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='short_address',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
