# Generated by Django 2.2.2 on 2019-07-07 04:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('okcvacants', '0014_property_short_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusTract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoid', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('county', models.IntegerField()),
                ('boundary', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='census_tract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='okcvacants.CensusTract'),
        ),
    ]
